function indexes = load_indexes(name_dataset)

indexes = [
    load("indexes\"+name_dataset+"\1.mat").indexes...
    load("indexes\"+name_dataset+"\2.mat").indexes...
    load("indexes\"+name_dataset+"\3.mat").indexes...
    load("indexes\"+name_dataset+"\4.mat").indexes...
    load("indexes\"+name_dataset+"\5.mat").indexes...
    ];

